services:
  - type: web
    name: support-triage-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"

  - type: background
    name: support-triage-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A app.core.celery_app.celery worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"